#! /bin/bash
#
# simple init script for gitlab-commit-trello-comment
#
#
# chkconfig: 345 99 01
# description: gitlab commit with trello card number will comment to that card.
#
# File : gitlab-commit-trello-comment

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

prog="/var/lib/puppet/gitlab-commit-trello-comment/gitlab-commit-trello-comment.py"
PROG_USER="puppet"
RETVAL=0

start () {
        echo -n "Starting $prog"
        /usr/bin/sudo -u $PROG_USER  "$prog" &
        RETVAL=$?
        [ $RETVAL -eq 0 ] && success || failure
        echo
}

stop () {
        echo -n "Stopping $prog"
        killproc gitlab-commit-trello-comment.py
        RETVAL=$?
        [ $RETVAL -eq 0 ] && success || failure
        echo
}

restart () {
        stop
        start
}


# See how we are called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo "Usage: service gitlab-commit-trello-comment {start|stop|restart|reload}"
        RETVAL=2
        ;;
esac

exit $RETVAL
